name: Daily C++ Compile Check

on:
  schedule:
    # 每天 UTC 0 点触发一次，按需改成你想要的时间
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  compile:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Inject headers and namespace, then compile
        shell: bash
        run: |
          # 1) 在 Header.hpp 开头插入依赖
          sed -i '1iusing namespace std;' Header.hpp
          sed -i '1i#include <bits/stdc++.h>' Header.hpp
          sed -i '1i#pragma once' Header.hpp

          # 2) 对其它所有 .hpp 文件插入依赖
          for f in *.hpp; do
            if [[ "$f" != "Header.hpp" ]]; then
              if [[ "$f" != "modint.hpp" ]]; then
                sed -i '1i#include "modint.hpp"' "$f"
              fi
              if [[ "$f" != "树状数组.hpp" ]]; then
                sed -i '1i#include "树状数组.hpp"' "$f"
              fi
              if [[ "$f" != "并查集.hpp" ]]; then
                sed -i '1i#include "并查集.hpp"' "$f"
              fi
              if [[ "$f" != "离散化.hpp" ]]; then
                sed -i '1i#include "离散化.hpp"' "$f"
              fi
              sed -i '1iusing namespace std;' "$f"
              sed -i '1i#include "Header.hpp"' "$f"
              sed -i '1i#include <bits/stdc++.h>' "$f"
              sed -i '1i#pragma once' "$f"
            fi
          done

          # 3) 尝试编译每个文件（若有工程文件可以改成编译整个工程）
          for f in *.hpp; do
            echo "Compiling $f..."
            g++ -std=c++17 -O2 -Wall -Wextra -fsyntax-only "$f"
          done

      - name: Revert all local modifications
        run: git checkout -- .