name: Generate C++ Headers PDF

on:
  schedule:
    - cron: '0 2 * * *'
  workflow_dispatch:

jobs:
  build_pdf:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          persist-credentials: true

      - name: Install Pandoc, LaTeX & Fonts
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            pandoc \
            texlive-xetex \
            texlive-latex-recommended \
            texlive-fonts-recommended \
            texlive-lang-chinese \
            fonts-noto-cjk \
            fonts-dejavu-core \
            fonts-dejavu-extra \
            fonts-jetbrains-mono

      - name: Generate Markdown for headers
        shell: bash
        run: |
          printf '%s\n' \
            '---' \
            'title: "C++ Header Files"' \
            'toc: true' \
            'toc-depth: 2' \
            'header-includes:' \
            '  - \usepackage{xeCJK}' \
            '---' \
          > HEADERS.md

          for file in *.hpp; do
            printf '## %s\n' "$file"     >> HEADERS.md
            printf '```cpp\n'            >> HEADERS.md
            sed 's/\t/    /g' "$file"    >> HEADERS.md
            printf '\n```\n\n'          >> HEADERS.md
          done

      - name: Convert Markdown to PDF via XeLaTeX
        run: |
          pandoc HEADERS.md \
            --toc --toc-depth=2 \
            --pdf-engine=xelatex \
            -V CJKmainfont="Noto Serif CJK SC" \
            -V mainfont="DejaVu Serif" \
            -V monofont="DejaVu Sans Mono" \
            -V geometry:margin=1in \
            -o headers.pdf

      - name: Commit & Push if changed
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name  "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add headers.pdf
          if git diff-index --quiet HEAD --; then
            echo "No changes to headers.pdf, skipping commit."
          else
            git commit -m "chore: generate headers PDF"
            git push
          fi