name: Generate C++ Headers PDF

on:
  schedule:
    - cron: '0 2 * * *'
  workflow_dispatch:

jobs:
  build_pdf:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          persist-credentials: true

      - name: Install Pandoc & LaTeX with CJK support
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            pandoc \
            texlive-xetex \
            texlive-latex-recommended \
            texlive-fonts-recommended \
            texlive-lang-chinese \
            fonts-noto-cjk

      - name: Generate Markdown for headers
        shell: bash
        run: |
          # 顶格写 metadata，保证 UTF-8
          printf '---\n'      > HEADERS.md
          printf 'title: "C++ Header Files"\n' >> HEADERS.md
          printf 'toc: true\n'                  >> HEADERS.md
          printf 'toc-depth: 2\n'               >> HEADERS.md
          printf 'header-includes:\n'           >> HEADERS.md
          printf '  - \\usepackage{xeCJK}\n'     >> HEADERS.md
          printf '---\n\n'                      >> HEADERS.md

          # 清理可能的 Windows CRLF
          dos2unix HEADERS.md &>/dev/null

          # 只处理 UTF-8 合法的 .hpp 文件
          for file in *.hpp; do
            if printf '%s' "$file" | iconv -f utf-8 -t utf-8 >/dev/null 2>&1; then
              printf '## %s\n\n' "$file"         >> HEADERS.md
              printf '```cpp\n'                 >> HEADERS.md
              sed 's/\t/    /g' "$file"         >> HEADERS.md
              printf '\n```\n\n'                >> HEADERS.md
            else
              echo "Skipping non-UTF8 filename: $file"
            fi
          done

      - name: Convert Markdown to PDF via XeLaTeX
        run: |
          pandoc HEADERS.md \
            --toc --toc-depth=2 \
            --pdf-engine=xelatex \
            -V CJKmainfont="Noto Serif CJK SC" \
            -V mainfont="DejaVu Serif" \
            -V geometry:margin=1in \
            -o headers.pdf

      - name: Commit & Push if changed
        shell: bash
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name  "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add headers.pdf
          if git diff-index --quiet HEAD --; then
            echo "No changes to headers.pdf, skipping commit."
          else
            git commit -m "chore: generate headers PDF"
            git push
          fi
