name: Generate C++ Headers PDF

on:
  schedule:
    - cron: '0 2 * * *'
  workflow_dispatch:

jobs:
  build_pdf:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          persist-credentials: true

      - name: install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            pandoc \
            texlive-xetex \
            texlive-latex-recommended \
            texlive-fonts-recommended \
            texlive-lang-chinese \
            fonts-noto-cjk \
            dos2unix

      - name: normalize and convert .hpp → UTF-8
        shell: bash
        run: |
          # 先去掉 Windows CRLF，再转换编码
          for f in *.hpp; do
            dos2unix "$f" &>/dev/null
            # 尝试把 GBK 转 UTF-8（如果原本不是 GBK 会失败，忽略错误）
            if iconv -f gb18030 -t utf-8 "$f" -o "${f}.utf8" 2>/dev/null; then
              mv "${f}.utf8" "$f"
            fi
          done

      - name: generate HEADERS.md
        shell: bash
        run: |
          # 写入 YAML metadata
          printf '%s\n' \
            '---' \
            'title: "C++ Header Files"' \
            'toc: true' \
            'toc-depth: 2' \
            'header-includes:' \
            '  - \usepackage{xeCJK}' \
            '---' \
          > HEADERS.md

          # 拼接每个 .hpp
          for file in *.hpp; do
            printf '## %s\n' "$file"     >> HEADERS.md
            printf '```cpp\n'            >> HEADERS.md
            sed 's/\t/    /g' "$file"    >> HEADERS.md
            printf '\n```\n\n'          >> HEADERS.md
          done

      - name: convert to PDF
        run: |
          pandoc HEADERS.md \
            --toc --toc-depth=2 \
            --pdf-engine=xelatex \
            -V CJKmainfont="Noto Serif CJK SC" \
            -V mainfont="DejaVu Serif" \
            -V geometry:margin=1in \
            -o headers.pdf

      - name: commit & push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name  "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add headers.pdf
          if git diff-index --quiet HEAD --; then
            echo "No changes to headers.pdf, skipping commit."
          else
            git commit -m "chore: generate headers PDF"
            git push
          fi