name: Generate C++ Headers PDF

on:
  schedule:
    - cron: '0 2 * * *'
  workflow_dispatch:

jobs:
  build_pdf:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          persist-credentials: true

      - name: Install Pandoc & LaTeX with CJK support
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            pandoc \
            texlive-xetex \
            texlive-latex-recommended \
            texlive-fonts-recommended \
            texlive-lang-chinese \
            fonts-noto-cjk

      - name: Generate Markdown for headers
        shell: bash
        run: |
          # 用 echo 写入 YAML metadata block
          echo '---'                > HEADERS.md
          echo 'title: "C++ Header Files"' >> HEADERS.md
          echo 'toc: true'          >> HEADERS.md
          echo 'toc-depth: 2'       >> HEADERS.md
          echo '---'                >> HEADERS.md

          # 遍历 .hpp 文件，添加二级标题和代码块
          for file in *.hpp; do
            echo "## ${file}"      >> HEADERS.md
            echo '```cpp'          >> HEADERS.md
            sed 's/\t/    /g' "$file" >> HEADERS.md
            echo '```'             >> HEADERS.md
            echo                   >> HEADERS.md
          done

      - name: Convert Markdown to PDF via XeLaTeX
        run: |
          pandoc HEADERS.md \
            --toc --toc-depth=2 \
            --pdf-engine=xelatex \
            -V CJKmainfont="Noto Serif CJK SC" \
            -V geometry:margin=1in \
            -o headers.pdf

      - name: Commit & Push if changed
        shell: bash
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name  "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add headers.pdf
          if git diff-index --quiet HEAD --; then
            echo "No changes to headers.pdf, skipping commit."
          else
            git commit -m "chore: generate headers PDF"
            git push
          fi