name: Generate C++ Headers PDF

on:
  schedule:
    - cron: '0 2 * * *'
  workflow_dispatch:

jobs:
  build_pdf:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          persist-credentials: true

      - name: Install Pandoc, LaTeX & fonts
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            pandoc \
            texlive-xetex \
            texlive-latex-recommended \
            texlive-fonts-recommended \
            texlive-lang-chinese \
            fonts-noto-cjk \
            fonts-dejavu-core \
            dos2unix

      - name: Normalize & convert headers to UTF-8
        shell: bash
        run: |
          for f in *.hpp; do
            dos2unix "$f" &>/dev/null
            if ! iconv -f utf-8 -t utf-8 "$f" -o /dev/null 2>/dev/null; then
              iconv -f gb18030 -t utf-8 "$f" -o "${f}.utf8" && mv "${f}.utf8" "$f"
            fi
          done

      - name: Generate HEADERS.md
        shell: bash
        run: |
          printf '%s\n' \
            '---' \
            'title: "C++ Header Files"' \
            'toc: true' \
            'toc-depth: 2' \
            'header-includes:' \
            '  - \usepackage{xeCJK}' \
            '  - \setCJKmonofont[Scale=MatchLowercase]{Noto Sans Mono CJK SC}' \
            '  - \usepackage{fvextra}' \
            '  - \fvset{breaklines=true,breakanywhere=true,breakindent=0pt}' \
            '---' \
          > HEADERS.md

          for file in *.hpp; do
            printf '## %s\n' "$file"     >> HEADERS.md
            printf '```cpp\n'            >> HEADERS.md
            sed 's/\t/    /g' "$file"    >> HEADERS.md
            printf '\n```\n\n'          >> HEADERS.md
          done

      - name: Ensure HEADERS.md is UTF-8
        shell: bash
        run: |
          iconv -f utf-8 -t utf-8 HEADERS.md -o HEADERS.tmp && mv HEADERS.tmp HEADERS.md

      - name: Convert to PDF via XeLaTeX
        run: |
          pandoc HEADERS.md \
            --toc --toc-depth=2 \
            --pdf-engine=xelatex \
            -V mainfont="DejaVu Serif" \
            -V monofont="DejaVu Sans Mono" \
            -V CJKmainfont="Noto Serif CJK SC" \
            -V geometry:margin=1in \
            -o headers.pdf

      - name: Commit & Push if changed
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name  "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add headers.pdf
          if git diff-index --quiet HEAD --; then
            echo "No changes to headers.pdf, skipping commit."
          else
            git commit -m "chore: generate headers PDF"
            git push
          fi
